[package]
name = "whatsys"
version = "0.3.2"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]
edition = "2018"
description = "Determine the kernel version"
license = "MIT"
repository = "https://github.com/badboy/whatsys"
rust-version = "1.95.0"

[package.metadata.docs.rs]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"

[workspace]
members = [
    ".",
    "windows-example"
]
default-members = ["."]
